# версия Docker Compose
version: '20.10.22'

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  # описание контейнера db
  db:
    # образ, из которого должен быть запущен контейнер
    image: postgres:13.7-alpine
    # volume и связанная с ним директория в контейнере
    volumes:
      - /var/lib/postgresql/data/
    # переменные окружения
    environment:
      - POSTGRES_DB=share_it
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=CHS2t1062

  web:
    build: .
    ports:
      - "8080:8080"
    # "зависит от",
    depends_on:
      - db
    # переменные окружения
    environment:
      - DB_NAME=share_it
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=CHS2t1062
      - DB_HOST=db
      - DB_PORT=5432