version: '20.10.22'
services:
  db:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=share_it
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=CHS2t1062

  server:
    image: amazoncorretto:11-alpine-jdk
    tty: true
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/share_it
      - DB_NAME=share_it
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=CHS2t1062
      - DB_HOST=db
      - DB_PORT=6541

  gateway:
    image: amazoncorretto:11-alpine-jdk
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

